### ISSUE TITLE
tree.md 功能优化

### ISSUE THREAD

**Issue by dkvirus** [teadocs/teadocs#24]
## 问题

目前，tree.md 中的文章都会在网页显示出来。
实际使用中，在学习新技术时，我希望用 teadocs 记录📝笔记，于是在 tree.md 中添加了一条记录；
打包时，teadocs 会把《Typescript 笔记》这份笔记也打包出来，但此时这只是笔记，内容很杂乱；
在未整理内容之前，我希望《Typescript 笔记》只是一份草稿，打包时不应该包含这篇文章。

``` md
- [介绍](/index)
- [Typescript 笔记](/typescript)
```

## 期待

tree.md 添加符号 `$`，打包的时候过滤所有 `$` 开头的文章。

``` md
- [介绍](/index)
- [$Typescript 笔记](/typescript)
```

## 补充

判断是开发还是生产环境，通过参数 dev 或者 build 可以得到。

- `teadocs dev` 阶段打包生成的文章应该包含所有文章；
- `teadocs build` 阶段打包生成的文章不包含 $ 开头的文章。

**Comment by lisniuse** [comment]
嗯，我觉得这个功能可以做。

**Comment by dkvirus** [comment]
好久没看到你更新 teadocs 动态了，还以为你不管这个项目了。 🤦‍♂️
