### ISSUE TITLE
自动递增端口

### ISSUE THREAD

**Issue by dkvirus** [teadocs/teadocs#25]
## 问题

本地有两个 teadocs 工程，启动第一个工程：

```
project1 $ teadocs dev 
```

启动第二个工程：

``` 
project2 $ teadocs dev
<====  报错，端口已启动，请重新指定端口
```

端口冲突，此时可以通过指定端口启动第二个项目：

``` 
project2 $ teadocs dev -p 3100
```

这很麻烦。

## 期望

起第二个工程时，会自动检测端口是否启动，如 3000 端口已启动，会自动递增启动 3001 端口。

类似这种模式在命令行工具中很常见，提升用户体验。

**Comment by lisniuse** [comment]
这个功能可以有。

**Comment by lisniuse** [comment]
另外，今天（2019.11.12）已经发布了 v 0.4.0 。
