### ISSUE TITLE
能不能加上编译的选项，本地编译出来如果想发布到gitpage上只能手动改css等的相对路径

### ISSUE THREAD

**Issue by Suchun-sv** [teadocs/teadocs#32]
如题，

**Comment by dkvirus** [comment]
没看明白要做什么。遇到什么问题？加什么选项？达到什么样的效果？

**Comment by orleven** [comment]
配合nginx时候，必须要配置static路径，否则样式不行， 能否加个配置，可以修改编译后的静态文件路径，或者改成相对的也行

**Comment by Suchun-sv** [comment]
不好意思，没仔细看配置文件。我原来的问题就是本地static文件的路径和发布到服务器上的不一样，修改的话只能手动改生成后的html里的src路径。现在是发现了配置文件里有选项可以自己指定静态文件的路径。
