### ISSUE TITLE
【需求】希望增加文章目录

### ISSUE THREAD

**Issue by dkvirus** [teadocs/teadocs#8]
### 需求

根据文章内的一级标题、二级标题、三级标题，生成文章目录，

- 一来看文章目录就可以知道大致要说哪些内容了；
- 二来文档本身是具有查询属性，点击对应目录标题，可以快速定位到标题所在位置。

### 方案

web 端页面右侧刚好有一片空白区域，可以用来放文章目录；

做成响应式，浏览器宽度小于一定值，不显示文章目录；

markdown 文档内没有用到一级标题、二级标题、三级标题的，不生成文章目录；

手机端由于屏幕太小，不显示文章目录。

@lisniuse  大佬看还有啥要补充的不~~~

### 示例网站

- [Ant-design 官方文档](https://ant.design/docs/react/introduce-cn)
- [Segmentfault](https://segmentfault.com/a/1190000019936984?utm_source=tag-newest#articleHeader3)

**Comment by lisniuse** [comment]
我赞同你的想法。👍

下面是我之前没有记录下来的需要优化的地方：

1. dev模式下监听md文件改动会重新build全部文件，我希望只build改动的文件，这样可以提高dev build速度。
2. 每次从左边的菜单点击章节跳转之后，左边的菜单栏会自动跳转到顶部去，希望可以优化成下一个页面会记录上一次菜单的滚动条位置。

欢迎你加入贡献代码！👏

**Comment by dkvirus** [comment]
@lisniuse  文章目录功能已添加。

上面👆两个功能点单独开 issue 跟踪了哈~~~

还有个小建议，很多开源库都整了个 `Roadmap for 1.x` 的 issue，有几个作用：

- 记录开发计划，有什么优化点或者新需求都可以记在那里，而不是记录普通 issue 中，普通 issue 关闭，不太方便跟踪未完成的开发任务；
- 发布新版本时，现成的 changelog； 
- 下方评论区可以作为大伙交流 idea 的场所；

参考：
- [Ant-design](https://github.com/ant-design/ant-design/issues)
- [Umijs](https://github.com/umijs/umi/issues)
